
// This file has been generated by the GUI designer. Do not modify.
namespace RestoranApp
{
	public partial class RegistracijaWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label1;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Entry entryIme;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label7;

		private global::Gtk.Fixed fixed8;

		private global::Gtk.Entry entryPrezime;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label2;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.Entry entryAdresa;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label3;

		private global::Gtk.Fixed fixed6;

		private global::Gtk.Entry entryBroj;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Fixed fixed7;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label5;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Entry entryEmail;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label6;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Entry entryLozinka;

		private global::Gtk.Fixed fixed11;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Fixed fixed13;

		private global::Gtk.Fixed fixed12;

		private global::Gtk.Button buttonPosalji;

		private global::Gtk.Fixed fixed9;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestoranApp.RegistracijaWindow
			this.Name = "RestoranApp.RegistracijaWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("RegistracijaWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			// Container child RestoranApp.RegistracijaWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(15));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.WidthRequest = 100;
			this.label1.HeightRequest = 35;
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Ime:");
			this.hbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.hbox1.Add(this.fixed4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed4]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryIme = new global::Gtk.Entry();
			this.entryIme.WidthRequest = 150;
			this.entryIme.HeightRequest = 30;
			this.entryIme.CanFocus = true;
			this.entryIme.Name = "entryIme";
			this.entryIme.IsEditable = true;
			this.entryIme.InvisibleChar = '●';
			this.hbox1.Add(this.entryIme);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryIme]));
			w3.Position = 2;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 100;
			this.label7.HeightRequest = 35;
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Prezime:");
			this.hbox6.Add(this.label7);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label7]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fixed8 = new global::Gtk.Fixed();
			this.fixed8.Name = "fixed8";
			this.fixed8.HasWindow = false;
			this.hbox6.Add(this.fixed8);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.fixed8]));
			w6.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryPrezime = new global::Gtk.Entry();
			this.entryPrezime.WidthRequest = 150;
			this.entryPrezime.HeightRequest = 30;
			this.entryPrezime.CanFocus = true;
			this.entryPrezime.Name = "entryPrezime";
			this.entryPrezime.IsEditable = true;
			this.entryPrezime.InvisibleChar = '●';
			this.hbox6.Add(this.entryPrezime);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryPrezime]));
			w7.Position = 2;
			this.vbox1.Add(this.hbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox6]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.WidthRequest = 100;
			this.label2.HeightRequest = 35;
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Ulica i kućni broj:");
			this.hbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.hbox3.Add(this.fixed5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.fixed5]));
			w10.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryAdresa = new global::Gtk.Entry();
			this.entryAdresa.WidthRequest = 150;
			this.entryAdresa.HeightRequest = 30;
			this.entryAdresa.CanFocus = true;
			this.entryAdresa.Name = "entryAdresa";
			this.entryAdresa.IsEditable = true;
			this.entryAdresa.InvisibleChar = '●';
			this.hbox3.Add(this.entryAdresa);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entryAdresa]));
			w11.Position = 2;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 100;
			this.label3.HeightRequest = 35;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Kontakt broj:");
			this.hbox4.Add(this.label3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label3]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.hbox4.Add(this.fixed6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.fixed6]));
			w14.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryBroj = new global::Gtk.Entry();
			this.entryBroj.WidthRequest = 150;
			this.entryBroj.HeightRequest = 30;
			this.entryBroj.CanFocus = true;
			this.entryBroj.Name = "entryBroj";
			this.entryBroj.IsEditable = true;
			this.entryBroj.InvisibleChar = '●';
			this.hbox4.Add(this.entryBroj);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entryBroj]));
			w15.Position = 2;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed7 = new global::Gtk.Fixed();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.hbox2.Add(this.fixed7);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed7]));
			w17.Position = 0;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w18.Position = 4;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.WidthRequest = 100;
			this.label5.HeightRequest = 35;
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("E-mail adresa:");
			this.hbox7.Add(this.label5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label5]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox7.Add(this.fixed1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.fixed1]));
			w20.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entryEmail = new global::Gtk.Entry();
			this.entryEmail.WidthRequest = 150;
			this.entryEmail.HeightRequest = 30;
			this.entryEmail.CanFocus = true;
			this.entryEmail.Name = "entryEmail";
			this.entryEmail.IsEditable = true;
			this.entryEmail.InvisibleChar = '●';
			this.hbox7.Add(this.entryEmail);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entryEmail]));
			w21.Position = 2;
			this.vbox1.Add(this.hbox7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox7]));
			w22.Position = 5;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 100;
			this.label6.HeightRequest = 35;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Lozinka:");
			this.hbox5.Add(this.label6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label6]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox5.Add(this.fixed2);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.fixed2]));
			w24.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryLozinka = new global::Gtk.Entry();
			this.entryLozinka.WidthRequest = 150;
			this.entryLozinka.HeightRequest = 30;
			this.entryLozinka.CanFocus = true;
			this.entryLozinka.Name = "entryLozinka";
			this.entryLozinka.IsEditable = true;
			this.entryLozinka.InvisibleChar = '●';
			this.hbox5.Add(this.entryLozinka);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.entryLozinka]));
			w25.Position = 2;
			this.vbox1.Add(this.hbox5);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox5]));
			w26.Position = 6;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed();
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			this.vbox1.Add(this.fixed11);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed11]));
			w27.Position = 7;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed13 = new global::Gtk.Fixed();
			this.fixed13.Name = "fixed13";
			this.fixed13.HasWindow = false;
			this.hbox8.Add(this.fixed13);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.fixed13]));
			w28.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed12 = new global::Gtk.Fixed();
			this.fixed12.Name = "fixed12";
			this.fixed12.HasWindow = false;
			this.hbox8.Add(this.fixed12);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.fixed12]));
			w29.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonPosalji = new global::Gtk.Button();
			this.buttonPosalji.WidthRequest = 70;
			this.buttonPosalji.HeightRequest = 45;
			this.buttonPosalji.CanFocus = true;
			this.buttonPosalji.Name = "buttonPosalji";
			this.buttonPosalji.UseUnderline = true;
			this.buttonPosalji.Label = global::Mono.Unix.Catalog.GetString("Pošalji");
			this.hbox8.Add(this.buttonPosalji);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonPosalji]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox1.Add(this.hbox8);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox8]));
			w31.Position = 8;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed9 = new global::Gtk.Fixed();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			this.vbox1.Add(this.fixed9);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed9]));
			w32.Position = 9;
			w32.Expand = false;
			w32.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 445;
			this.Show();
		}
	}
}
