
// This file has been generated by the GUI designer. Do not modify.
namespace RestoranApp
{
	public partial class NarucivanjeWindow
	{
		private global::Gtk.VBox vboxMain;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestoranApp.NarucivanjeWindow
			this.Name = "RestoranApp.NarucivanjeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("NarucivanjeWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(10));
			// Container child RestoranApp.NarucivanjeWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 481;
			this.DefaultHeight = 328;
			this.Show();
		}
	}
}
