
// This file has been generated by the GUI designer. Do not modify.
namespace RestoranApp
{
	public partial class PrijavaWindow
	{
		private global::Gtk.VBox vbox3;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label Email1;

		private global::Gtk.Fixed fixed14;

		private global::Gtk.Entry entryMail;

		private global::Gtk.Fixed fixed15;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label Lozinka1;

		private global::Gtk.Fixed fixed16;

		private global::Gtk.Entry entryLozinka;

		private global::Gtk.Fixed fixed17;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Fixed fixed19;

		private global::Gtk.Fixed fixed18;

		private global::Gtk.Button buttonPrijava;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestoranApp.PrijavaWindow
			this.Name = "RestoranApp.PrijavaWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("PrijavaWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			// Container child RestoranApp.PrijavaWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Email1 = new global::Gtk.Label();
			this.Email1.WidthRequest = 130;
			this.Email1.HeightRequest = 35;
			this.Email1.Name = "Email1";
			this.Email1.LabelProp = global::Mono.Unix.Catalog.GetString("E-mail adresa:");
			this.hbox6.Add(this.Email1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.Email1]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fixed14 = new global::Gtk.Fixed();
			this.fixed14.Name = "fixed14";
			this.fixed14.HasWindow = false;
			this.hbox6.Add(this.fixed14);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.fixed14]));
			w2.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entryMail = new global::Gtk.Entry();
			this.entryMail.CanFocus = true;
			this.entryMail.Name = "entryMail";
			this.entryMail.IsEditable = true;
			this.entryMail.InvisibleChar = '●';
			this.hbox6.Add(this.entryMail);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entryMail]));
			w3.Position = 2;
			this.vbox3.Add(this.hbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed15 = new global::Gtk.Fixed();
			this.fixed15.Name = "fixed15";
			this.fixed15.HasWindow = false;
			this.vbox3.Add(this.fixed15);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixed15]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.Lozinka1 = new global::Gtk.Label();
			this.Lozinka1.WidthRequest = 130;
			this.Lozinka1.HeightRequest = 35;
			this.Lozinka1.Name = "Lozinka1";
			this.Lozinka1.LabelProp = global::Mono.Unix.Catalog.GetString("Lozinka:");
			this.hbox7.Add(this.Lozinka1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.Lozinka1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.fixed16 = new global::Gtk.Fixed();
			this.fixed16.Name = "fixed16";
			this.fixed16.HasWindow = false;
			this.hbox7.Add(this.fixed16);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.fixed16]));
			w7.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entryLozinka = new global::Gtk.Entry();
			this.entryLozinka.CanFocus = true;
			this.entryLozinka.Name = "entryLozinka";
			this.entryLozinka.IsEditable = true;
			this.entryLozinka.InvisibleChar = '●';
			this.hbox7.Add(this.entryLozinka);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entryLozinka]));
			w8.Position = 2;
			this.vbox3.Add(this.hbox7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed17 = new global::Gtk.Fixed();
			this.fixed17.Name = "fixed17";
			this.fixed17.HasWindow = false;
			this.vbox3.Add(this.fixed17);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixed17]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed19 = new global::Gtk.Fixed();
			this.fixed19.Name = "fixed19";
			this.fixed19.HasWindow = false;
			this.hbox8.Add(this.fixed19);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.fixed19]));
			w11.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.fixed18 = new global::Gtk.Fixed();
			this.fixed18.Name = "fixed18";
			this.fixed18.HasWindow = false;
			this.hbox8.Add(this.fixed18);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.fixed18]));
			w12.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonPrijava = new global::Gtk.Button();
			this.buttonPrijava.WidthRequest = 80;
			this.buttonPrijava.HeightRequest = 40;
			this.buttonPrijava.CanFocus = true;
			this.buttonPrijava.Name = "buttonPrijava";
			this.buttonPrijava.UseUnderline = true;
			this.buttonPrijava.Label = global::Mono.Unix.Catalog.GetString("Prijavi se");
			this.hbox8.Add(this.buttonPrijava);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonPrijava]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox3.Add(this.hbox8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			this.Add(this.vbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
