
// This file has been generated by the GUI designer. Do not modify.
namespace RestoranApp
{
	public partial class CjenikWindow
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label2;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Label label3;

		private global::Gtk.Label label8;

		private global::Gtk.Label label1;

		private global::Gtk.Label label9;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label4;

		private global::Gtk.VBox vboxUmak;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label5;

		private global::Gtk.VBox vboxMeso;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vboxSir;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Label label7;

		private global::Gtk.VBox vboxPrilozi;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestoranApp.CjenikWindow
			this.Name = "RestoranApp.CjenikWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("CjenikWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child RestoranApp.CjenikWindow.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("NARUČIVANJE HRANE");
			this.vbox7.Add(this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Odaberi jelo");
			this.vbox9.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label3]));
			w2.Position = 0;
			w2.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Pizza (20 kn)");
			this.vbox9.Add(this.label8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label8]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Hamburger (5 kn)");
			this.vbox9.Add(this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label1]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Tortilja (10 kn)");
			this.vbox9.Add(this.label9);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label9]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox5.Add(this.vbox9);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox9]));
			w6.Position = 0;
			w6.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Umak");
			this.vbox2.Add(this.label4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vboxUmak = new global::Gtk.VBox();
			this.vboxUmak.Name = "vboxUmak";
			this.vboxUmak.Spacing = 6;
			this.vbox2.Add(this.vboxUmak);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vboxUmak]));
			w8.Position = 1;
			this.hbox5.Add(this.vbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox2]));
			w9.Position = 1;
			w9.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Meso");
			this.vbox3.Add(this.label5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label5]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vboxMeso = new global::Gtk.VBox();
			this.vboxMeso.Name = "vboxMeso";
			this.vboxMeso.Spacing = 6;
			this.vbox3.Add(this.vboxMeso);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vboxMeso]));
			w11.Position = 1;
			this.hbox5.Add(this.vbox3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox3]));
			w12.Position = 2;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Sir");
			this.vbox4.Add(this.label6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label6]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vboxSir = new global::Gtk.VBox();
			this.vboxSir.Name = "vboxSir";
			this.vboxSir.Spacing = 6;
			this.vbox4.Add(this.vboxSir);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vboxSir]));
			w14.Position = 1;
			this.hbox5.Add(this.vbox4);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox4]));
			w15.Position = 3;
			w15.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Prilozi");
			this.vbox5.Add(this.label7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label7]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vboxPrilozi = new global::Gtk.VBox();
			this.vboxPrilozi.Name = "vboxPrilozi";
			this.vboxPrilozi.Spacing = 6;
			this.vbox5.Add(this.vboxPrilozi);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vboxPrilozi]));
			w17.Position = 1;
			this.hbox5.Add(this.vbox5);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox5]));
			w18.Position = 4;
			w18.Fill = false;
			this.vbox7.Add(this.hbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w19.Position = 1;
			w19.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 704;
			this.DefaultHeight = 382;
			this.Show();
		}
	}
}
