
// This file has been generated by the GUI designer. Do not modify.
namespace RestoranApp
{
	public partial class StatusNarudzbeWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestoranApp.StatusNarudzbeWindow
			this.Name = "RestoranApp.StatusNarudzbeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("StatusNarudzbeWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child RestoranApp.StatusNarudzbeWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add(this.nodeview1);
			this.Add(this.GtkScrolledWindow);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 573;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
