
// This file has been generated by the GUI designer. Do not modify.
namespace RestoranApp
{
	public partial class PocetnaWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button buttonRegistracija;

		private global::Gtk.Button buttonPrijava;

		private global::Gtk.Label label3;

		private global::Gtk.Fixed fixed1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestoranApp.PocetnaWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "RestoranApp.PocetnaWidget";
			// Container child RestoranApp.PocetnaWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.hbox1.Add(this.fixed2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed2]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonRegistracija = new global::Gtk.Button();
			this.buttonRegistracija.WidthRequest = 80;
			this.buttonRegistracija.HeightRequest = 40;
			this.buttonRegistracija.CanFocus = true;
			this.buttonRegistracija.Name = "buttonRegistracija";
			this.buttonRegistracija.UseUnderline = true;
			this.buttonRegistracija.Label = global::Mono.Unix.Catalog.GetString("Registracija");
			this.hbox1.Add(this.buttonRegistracija);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonRegistracija]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonPrijava = new global::Gtk.Button();
			this.buttonPrijava.WidthRequest = 80;
			this.buttonPrijava.HeightRequest = 40;
			this.buttonPrijava.CanFocus = true;
			this.buttonPrijava.Name = "buttonPrijava";
			this.buttonPrijava.UseUnderline = true;
			this.buttonPrijava.Label = global::Mono.Unix.Catalog.GetString("Prijava");
			this.hbox1.Add(this.buttonPrijava);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonPrijava]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.HeightRequest = 150;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("RESTORAN");
			this.vbox1.Add(this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			w5.Padding = ((uint)(11));
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.HeightRequest = 100;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox1.Add(this.fixed1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
