
// This file has been generated by the GUI designer. Do not modify.
namespace RestoranApp
{
	public partial class NarudzbaWidget
	{
		private global::Gtk.VButtonBox vbuttonbox3;

		private global::Gtk.Button buttonCjenik;

		private global::Gtk.Button buttonNaruci;

		private global::Gtk.Button buttonStatus;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestoranApp.NarudzbaWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "RestoranApp.NarudzbaWidget";
			// Container child RestoranApp.NarudzbaWidget.Gtk.Container+ContainerChild
			this.vbuttonbox3 = new global::Gtk.VButtonBox();
			this.vbuttonbox3.Name = "vbuttonbox3";
			this.vbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCjenik = new global::Gtk.Button();
			this.buttonCjenik.CanFocus = true;
			this.buttonCjenik.Name = "buttonCjenik";
			this.buttonCjenik.UseUnderline = true;
			this.buttonCjenik.Label = global::Mono.Unix.Catalog.GetString("Cjenik");
			this.vbuttonbox3.Add(this.buttonCjenik);
			global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3[this.buttonCjenik]));
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.buttonNaruci = new global::Gtk.Button();
			this.buttonNaruci.CanFocus = true;
			this.buttonNaruci.Name = "buttonNaruci";
			this.buttonNaruci.UseUnderline = true;
			this.buttonNaruci.Label = global::Mono.Unix.Catalog.GetString("Naruči");
			this.vbuttonbox3.Add(this.buttonNaruci);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3[this.buttonNaruci]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.buttonStatus = new global::Gtk.Button();
			this.buttonStatus.CanFocus = true;
			this.buttonStatus.Name = "buttonStatus";
			this.buttonStatus.UseUnderline = true;
			this.buttonStatus.Label = global::Mono.Unix.Catalog.GetString("Status");
			this.vbuttonbox3.Add(this.buttonStatus);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3[this.buttonStatus]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add(this.vbuttonbox3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
