
// This file has been generated by the GUI designer. Do not modify.
namespace RestoranApp
{
	public partial class TijekNarudzbeWidget
	{
		private global::Gtk.VButtonBox vbuttonbox4;

		private global::Gtk.Button buttonZaprimljeno;

		private global::Gtk.Button buttonPriprema;

		private global::Gtk.Button buttonDostava;

		private global::Gtk.Button buttonIzvrseno;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RestoranApp.TijekNarudzbeWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "RestoranApp.TijekNarudzbeWidget";
			// Container child RestoranApp.TijekNarudzbeWidget.Gtk.Container+ContainerChild
			this.vbuttonbox4 = new global::Gtk.VButtonBox();
			this.vbuttonbox4.Name = "vbuttonbox4";
			this.vbuttonbox4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.buttonZaprimljeno = new global::Gtk.Button();
			this.buttonZaprimljeno.CanFocus = true;
			this.buttonZaprimljeno.Name = "buttonZaprimljeno";
			this.buttonZaprimljeno.UseUnderline = true;
			this.buttonZaprimljeno.Label = global::Mono.Unix.Catalog.GetString("Zaprimljene narudžbe");
			this.vbuttonbox4.Add(this.buttonZaprimljeno);
			global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4[this.buttonZaprimljeno]));
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPriprema = new global::Gtk.Button();
			this.buttonPriprema.CanFocus = true;
			this.buttonPriprema.Name = "buttonPriprema";
			this.buttonPriprema.UseUnderline = true;
			this.buttonPriprema.Label = global::Mono.Unix.Catalog.GetString("Narudžbe u pripremi");
			this.vbuttonbox4.Add(this.buttonPriprema);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4[this.buttonPriprema]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.buttonDostava = new global::Gtk.Button();
			this.buttonDostava.CanFocus = true;
			this.buttonDostava.Name = "buttonDostava";
			this.buttonDostava.UseUnderline = true;
			this.buttonDostava.Label = global::Mono.Unix.Catalog.GetString("Dostava");
			this.vbuttonbox4.Add(this.buttonDostava);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4[this.buttonDostava]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.buttonIzvrseno = new global::Gtk.Button();
			this.buttonIzvrseno.CanFocus = true;
			this.buttonIzvrseno.Name = "buttonIzvrseno";
			this.buttonIzvrseno.UseUnderline = true;
			this.buttonIzvrseno.Label = global::Mono.Unix.Catalog.GetString("Izvršena narudžba");
			this.vbuttonbox4.Add(this.buttonIzvrseno);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4[this.buttonIzvrseno]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbuttonbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
